services:
  - type: web
    name: Organic-Rankine-Cycle
    env: python
    buildCommand: |
      # Install Chrome and ChromeDriver
      apt-get update && apt-get install -y wget unzip curl chromium-browser chromium-chromedriver
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    region: oregon
    plan: free
