services:
  - type: web
    name: Organic-Rankine-Cycle
    env: python
    buildCommand: |
      # Install dependencies
      apt-get update && apt-get install -y wget unzip curl

      # Create a writable directory for Chrome and ChromeDriver
      mkdir -p /opt/render/project/src/bin

      # Download and install a specific version of Google Chrome
      wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb -O /opt/render/project/src/bin/google-chrome-stable.deb
      dpkg-deb -x /opt/render/project/src/bin/google-chrome-stable.deb /opt/render/project/src/bin/google-chrome
      export PATH=/opt/render/project/src/bin/google-chrome/opt/google/chrome:$PATH

      # Verify the manually installed Google Chrome version
      echo "Verifying manually installed Google Chrome..."
      /opt/render/project/src/bin/google-chrome/opt/google/chrome/google-chrome --version || { echo "Google Chrome installation failed."; exit 1; }

      # Download and install a matching ChromeDriver version
      CHROMEDRIVER_VERSION="114.0.5735.90"
      wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -O /opt/render/project/src/bin/chromedriver_linux64.zip
      unzip /opt/render/project/src/bin/chromedriver_linux64.zip -d /opt/render/project/src/bin/
      chmod +x /opt/render/project/src/bin/chromedriver

      # Install Python dependencies
      pip install -r requirements.txt

    startCommand: |
      # Verify Chrome and ChromeDriver installation
      echo "Verifying Chrome and ChromeDriver installation..."
      /opt/render/project/src/bin/google-chrome/opt/google/chrome/google-chrome --version
      /opt/render/project/src/bin/chromedriver --version

      # Start the Streamlit application
      streamlit run app.py --server.port $PORT --server.address 0.0.0.0

    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
    region: oregon
    plan: free


