services:
  - type: web
    name: Organic-Rankine-Cycle
    env: python
    buildCommand: |
    # Install wget and unzip
    apt-get update && apt-get install -y wget unzip curl || true
    # Download and install the latest ChromeDriver
    CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
    wget -q https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -O /tmp/chromedriver.zip
    unzip /tmp/chromedriver.zip -d /opt/render/project/src/
    chmod +x /opt/render/project/src/chromedriver
    echo "ChromeDriver installed at /opt/render/project/src/chromedriver"
    # Install Chromium manually if necessary
    apt-get install -y chromium-browser || echo "Chromium install skipped"
    echo "PATH=$PATH:/opt/render/project/src/" >> /opt/render/.env
    # Install Python dependencies
    pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    region: oregon
    plan: free

