services:
  - type: web
    name: Organic-Rankine-Cycle
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wget unzip curl
      apt-get install -y chromium-browser chromium-chromedriver
      export CHROMEDRIVER_PATH=$(which chromedriver)
      export CHROMIUM_PATH=$(which chromium-browser)
      echo "ChromeDriver Path: $CHROMEDRIVER_PATH"
      echo "Chromium Path: $CHROMIUM_PATH"
      chromium-browser --version || echo "Chromium version not available"
      chromedriver --version || echo "Chromedriver version not available"
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    region: oregon
    plan: free
