services:
  - type: web
    name: Organic-Rankine-Cycle
    env: python
    buildCommand: |
      # Install dependencies
      apt-get update && apt-get install -y wget unzip curl xz-utils binutils

      # Create a writable directory for Chrome and ChromeDriver
      mkdir -p /opt/render/project/src/bin

      # Download Google Chrome .deb file
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /opt/render/project/src/bin/google-chrome-stable.deb

      # Inspect the .deb file contents for debugging
      echo "Inspecting the downloaded Google Chrome .deb file..."
      ar t /opt/render/project/src/bin/google-chrome-stable.deb || { echo "Failed to inspect .deb file."; exit 1; }

      # Extract the .deb file
      ar x /opt/render/project/src/bin/google-chrome-stable.deb -C /opt/render/project/src/bin/
      echo "Contents of /opt/render/project/src/bin after extraction:"
      ls -l /opt/render/project/src/bin/

      # Extract data.tar.xz if it exists
      if [ -f /opt/render/project/src/bin/data.tar.xz ]; then
        tar -xvf /opt/render/project/src/bin/data.tar.xz -C /opt/render/project/src/bin/
      else
        echo "Error: data.tar.xz not found in the .deb file."
        exit 1
      fi

      # Debug: Verify extracted directory structure
      echo "Checking extracted Google Chrome structure..."
      ls -l /opt/render/project/src/bin/

      # Set the Chrome binary path explicitly
      export CHROME_BINARY="/opt/render/project/src/bin/opt/google/chrome/google-chrome"

      # Verify manually installed Google Chrome version
      echo "Verifying manually installed Google Chrome..."
      $CHROME_BINARY --version || { echo "Google Chrome installation failed."; exit 1; }

      # Download ChromeDriver matching the manually installed Chrome
      CHROMEDRIVER_VERSION="114.0.5735.90"
      wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -O /opt/render/project/src/bin/chromedriver_linux64.zip
      unzip /opt/render/project/src/bin/chromedriver_linux64.zip -d /opt/render/project/src/bin/
      chmod +x /opt/render/project/src/bin/chromedriver

      # Verify ChromeDriver installation
      echo "Verifying ChromeDriver installation..."
      /opt/render/project/src/bin/chromedriver --version || { echo "ChromeDriver installation failed."; exit 1; }

      # Install Python dependencies
      pip install -r requirements.txt

    startCommand: |
      # Set environment variables explicitly
      export PATH="/opt/render/project/src/bin/opt/google/chrome:$PATH"
      export CHROME_BINARY="/opt/render/project/src/bin/opt/google/chrome/google-chrome"

      # Verify Chrome and ChromeDriver during runtime
      echo "Verifying runtime Chrome and ChromeDriver installation..."
      $CHROME_BINARY --version
      /opt/render/project/src/bin/chromedriver --version

      # Start the Streamlit application
      streamlit run app.py --server.port $PORT --server.address 0.0.0.0

    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
    region: oregon
    plan: free


