services:
  - type: web
    name: Organic-Rankine-Cycle
    env: python
    buildCommand: |
      # Install dependencies
      apt-get update && apt-get install -y wget unzip curl

      # Create a writable directory for Chrome and ChromeDriver
      mkdir -p /opt/render/project/src/bin

      # Download portable Google Chrome binary (Linux stable version)
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.tar.gz -O /opt/render/project/src/bin/google-chrome.tar.gz
      tar -xvzf /opt/render/project/src/bin/google-chrome.tar.gz -C /opt/render/project/src/bin/
      export PATH=/opt/render/project/src/bin/google-chrome:$PATH

      # Download matching ChromeDriver version
      CHROMEDRIVER_VERSION="114.0.5735.90"
      wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -O /opt/render/project/src/bin/chromedriver_linux64.zip
      unzip /opt/render/project/src/bin/chromedriver_linux64.zip -d /opt/render/project/src/bin/
      chmod +x /opt/render/project/src/bin/chromedriver

      # Verify installation of Chrome and ChromeDriver
      echo "Verifying Google Chrome installation..."
      /opt/render/project/src/bin/google-chrome/google-chrome --version || { echo "Google Chrome installation failed."; exit 1; }
      echo "Verifying ChromeDriver installation..."
      /opt/render/project/src/bin/chromedriver --version || { echo "ChromeDriver installation failed."; exit 1; }

      # Install Python dependencies
      pip install -r requirements.txt

    startCommand: |
      # Verify Chrome and ChromeDriver during runtime
      echo "Verifying runtime Chrome and ChromeDriver installation..."
      /opt/render/project/src/bin/google-chrome/google-chrome --version
      /opt/render/project/src/bin/chromedriver --version

      # Start the Streamlit application
      streamlit run app.py --server.port $PORT --server.address 0.0.0.0

    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
    region: oregon
    plan: free


